### ISSUE TITLE
Another Strange Bug

### ISSUE THREAD

**Issue by Dawnwalker666** [Zoko061602/Thaumic-Wands#19]
As you can see, there is another strange bug here.  It seems I can't craft anything.  Because when I exit the Arcane Worktable GUI, the wand will always disappear.
This is using thaumicwands-1.2.2, and forge 14.23.5.2854.
![02](https://user-images.githubusercontent.com/49862610/89986994-e81fb100-dcaf-11ea-8150-dcd41bbbd90c.gif)

**Comment by Dawnwalker666** [comment]
Another picture with version information, although it's in Chinese.

![02-1](https://user-images.githubusercontent.com/49862610/90013444-dd791200-dcd7-11ea-8535-3d2b11e579fb.gif)

**Comment by Zokonius** [comment]
could you also provide your log file when doing this ?

**Comment by Dawnwalker666** [comment]
> 
> 
> could you also provide your log file when doing this ?

[logs.zip](https://github.com/Zoko061602/Thaumic-Wands/files/5064103/logs.zip)

When I try to take the wand on the arcane worktable before exiting the GUI, the staff will still disappear.
![02](https://user-images.githubusercontent.com/49862610/90040382-715bd580-dcfa-11ea-8c3d-006f6d6f779b.gif)

**Comment by Zokonius** [comment]
This should be fixed in v1.2.3 looks like something went wrong when adding the additional slot to the worktable.

**Comment by Sixdd6** [comment]
Still an issue in 1.2.5
reference #24
