### ISSUE TITLE
Animation display problem

### ISSUE THREAD

**Issue by Dawnwalker666** [Zoko061602/Thaumic-Wands#25]
Normally, The wand placed on the arcane crafting table should have gradient animation .But if you move the view, the animation effect will disappear.
![02](https://user-images.githubusercontent.com/49862610/90627405-76ff7100-e24e-11ea-9a7c-772dddc5872d.gif)

When I have the **Unnatural Hunger** effect, the vis orb look so weird.
![02](https://user-images.githubusercontent.com/49862610/90628206-cd20e400-e24f-11ea-9e6a-5df558aad160.gif)

The problem that the wand disappear, has fixed in the new save.But the problem **still exist**s with the old save where the mod had been run.

At last, I download the mod with v1.2.5 at curseforge, but the mod information (mcmod.info) tells me that in 1.2.4.
![Screenshot_2020-03-09-13-53-45-05](https://user-images.githubusercontent.com/49862610/90629858-a1ebc400-e252-11ea-97a8-53037a4c894b.png)

**Comment by FurryJack0420** [comment]
I think it's something to do with another mod, I also have the same issue and I assumed it was because the lack of colored lux, but that mod made everything have wonky animations, like the terrain disappearing and all entities being white and flashing

**Comment by Dawnwalker666** [comment]
> I think it's something to do with another mod, I also have the same issue and I assumed it was because the lack of colored lux, but that mod made everything have wonky animations, like the terrain disappearing and all entities being white and flashing

This problem also exists in the thaumcraft. But I'm not sure if these animations is caused by this mod .So I issued.
