### ISSUE TITLE
Greatwood wand rod research prerequisites

### ISSUE THREAD

**Issue by FurryJack0420** [Zoko061602/Thaumic-Wands#28]
I'm trying to make a wand using a greatwood rod however the prerequisites for it's research are not listed anywhere not even on curse. is there any reason for this? It just says - ?

**Comment by FurryJack0420** [comment]
![2020-09-14_08 44 33](https://user-images.githubusercontent.com/50533178/93087520-aa26fb80-f666-11ea-9f44-87f3c0bb6abf.png)

**Comment by FurryJack0420** [comment]
Everything else needs infusion, and the rest of the wands need the greatwood rod research.
but I can't get infusion because It needs 150 vis to make the matrix and greatwood is the only thing that can hold more than that

**Comment by Zokonius** [comment]
Greatwood requires !PLANTWOOD , you can get that research from scanning Thaumcraft trees.
