### ISSUE TITLE
[Suggestion] Add wand caps for more modded materials

### ISSUE THREAD

**Issue by Keldera** [Zoko061602/Thaumic-Wands#3]
I think it would be cool if more modded materials could be made into caps, specifically I'm thinking about Mithrillium, Adaminite and Mithminite from Thaumic Additions: Reconstructed. With that mod installed those three tiers of material are available and are quite powerful, I think it would be fitting to have a crossover with it to continue their toolsets.

**Comment by Zokonius** [comment]
I already asked the maker of thaumic additions, if he wants to provide wandcaps, but he said he doesn't know how to balance it (as if Thaumic Additions is balanced), so I will probably add the code myself, if he allows it.

**Comment by Keldera** [comment]
oh cool :)

**Comment by Zokonius** [comment]
Wand Parts will be added in the next update of Thaumic Additions, I don't know when it realeses, but it is there.

**Comment by Keldera** [comment]
Nice!
